japan/urls.py
from django.contrib import admin
from django.conf.urls import patterns, include, url
import settings
from japanstudy.views import TestWordListView, TestingWordResultView, TestSessionListView, JapaneseWordListView
admin.autodiscover()
from dajaxice.core import dajaxice_autodiscover, dajaxice_config
dajaxice_autodiscover()

urlpatterns = [
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin_tools/', include('admin_tools.urls')),
    url(r'^add-word$', 'japanstudy.views.add_japan_word', name='add-japan-word'),
    url(r'add-word-advance', 'japanstudy.views.add_japan_word_advance', name='add-japan-word-advance'),
    url(r'words-list', JapaneseWordListView.as_view(), name='words-list'),
    url(r'^$', 'japanstudy.views.home', name='home'),
    url(r'^add-word-success', 'japanstudy.views.add_word_success', name='add_word_success'),
    url(r'^add-test-case', 'japanstudy.views.add_test_case', name='add-test-case'),
    url(r'^test-cases', TestWordListView.as_view(), name='test-cases-list'),
    url(r'^start-test-word/(?P<pk>\d+)', 'japanstudy.views.start_test_word', name='start-test-word'),
    url(r'^test-word/(?P<test_session_pk>\d+)/(?P<order>\d+)', 'japanstudy.views.test_word_session', name='test-word-session'),
    url(r'^test-word-result/(?P<test_session_pk>\d+)', TestingWordResultView.as_view(), name='test-word-session-result'),
    url(r'^test-session-list', TestSessionListView.as_view(), name='test-session-list'),
]
# STATIC
urlpatterns += patterns('', (
    r'^static/(?P<path>.*)$',
    'django.views.static.serve',
    {'document_root': settings.STATIC_ROOT}
))
# MEDIA
urlpatterns += patterns('', (
    r'^media/(?P<path>.*)$',
    'django.views.static.serve',
    {'document_root': settings.MEDIA_ROOT}
))

japanstudy/models.py
# -*- coding: utf-8 -*- 
from django.db import models
from django.contrib.auth.models import User 
from django.core.validators import MinValueValidator
from django.template.defaultfilters import default
from django.db.models import Q
STATUS = (('Y', 'Y'), ('N', 'N'))
JAPANESE_WORD_TYPE = ((True, 'Hiragana'), (False, 'Katakana'))
class Tag(models.Model):
    name = models.CharField(max_length=100, blank=False, verbose_name="Tên")
    description = models.TextField(max_length=500, null=True, blank=True, verbose_name="Mô tả")
    active = models.CharField(max_length=2, choices=STATUS, default='Y', verbose_name="Trạng thái")
    created_time = models.DateTimeField(auto_now_add=True, blank=True, verbose_name="Ngày tạo")
    user = models.ForeignKey(User, verbose_name="Người tạo")
    def __unicode__(self):
        return self.name
class Word(models.Model):
    source = models.CharField(max_length=200, blank=False, verbose_name="Từ")
    mean = models.CharField(max_length=200, blank=False, verbose_name="Nghĩa")
    other_mean = models.TextField(max_length=500, null=True, blank=True, verbose_name="Nghĩa khác")
    level = models.PositiveSmallIntegerField(validators=[MinValueValidator(0)], default=0, blank=False, verbose_name="Độ khó")
    description = models.TextField(max_length=500, null=True, blank=True, verbose_name="Mô tả")
    example = models.TextField(max_length=500, null=True, blank=True, verbose_name="Ví dụ")
    user = models.ForeignKey(User, verbose_name="Người tạo")
    tags = models.ManyToManyField(Tag, blank=True, verbose_name="Tag")
    sames = models.ManyToManyField('self', blank=True, verbose_name="Từ cùng nghĩa")
    created_time = models.DateTimeField(auto_now_add=True, blank=True, verbose_name="Ngày tạo")
    active = models.CharField(max_length=2, choices=STATUS, default='Y', verbose_name="Trạng thái")
    temp = models.BooleanField(default=False, blank=False, verbose_name="Dữ liệu tạm")
    def __unicode__(self):
        return "%s - %s " % (self.source, self.mean)
    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.id and len(Word.objects.filter(source=self.source, mean=self.mean)):
            return
        if self.id and len(Word.objects.filter(~Q(id=self.id), source=self.source, mean=self.mean)):
            return
        return models.Model.save(self, force_insert=force_insert, force_update=force_update, using=using, update_fields=update_fields)
class JapaneseWord(Word):
    kanji = models.CharField(max_length=200, blank=True, null=True, verbose_name="Từ Kanji")
    romaji = models.CharField(max_length=200, blank=True, null=True, verbose_name="Phiên âm Latinh")
    type = models.BooleanField(default=True, choices=JAPANESE_WORD_TYPE, verbose_name="Loại từ", blank=False)
    def __unicode__(self):
        return Word.__unicode__(self)
class AddWordSession(models.Model):
    japanese_words = models.ManyToManyField(JapaneseWord, blank=True, verbose_name="Từ được thêm")
    user = models.ForeignKey(User, verbose_name="Người tạo")
    current = models.BooleanField(default=True, blank=True, verbose_name="Đang sử dụng")
    created_time = models.DateTimeField(auto_now_add=True, blank=True, verbose_name="Ngày tạo")
    active = models.CharField(max_length=2, choices=STATUS, default='Y', verbose_name="Trạng thái")
    def __unicode__(self):
        return self.user.__str__()
class TestWord(models.Model):
    title = models.CharField(max_length=200, blank=False, verbose_name="Tiêu đề")
    words = models.ManyToManyField(JapaneseWord, blank=False, verbose_name="Gồm các từ")
    start_date = models.DateTimeField(null=True, blank=True, verbose_name="Ngày bắt đầu")
    completed_time = models.DateTimeField(null=True, blank=True, verbose_name="Ngày hoàn thành")
    created_time = models.DateTimeField(auto_now_add=True, blank=True, verbose_name="Ngày tạo")
    user = models.ForeignKey(User, verbose_name="Người tạo")
    active = models.CharField(max_length=2, choices=STATUS, default='Y', verbose_name="Trạng thái")
    def __unicode__(self):
        return self.title
    def get_shuffle_words(self):
        return self.words.order_by('?')
class TestSessionWordOrder(models.Model):
    order=models.PositiveSmallIntegerField(verbose_name="Thứ tự")
    word=models.ForeignKey(JapaneseWord, verbose_name="Từ")
    current=models.BooleanField(default=False, verbose_name="Từ hiện tại")
    correct = models.BooleanField(default=False, blank=True, verbose_name="Chính xác")
    completed = models.BooleanField(default=False, verbose_name="Hoàn thành")
    start = models.DateTimeField(null=True, blank=True, verbose_name="Bắt đầu")
    end = models.DateTimeField(null=True, blank=True, verbose_name="Kết thúc")
    def __unicode__(self):
        return unicode(self.word) or u''
class TestSession(models.Model):
    test_word = models.ForeignKey(TestWord, verbose_name="Bài test")
    test_session_word_orders = models.ManyToManyField(TestSessionWordOrder, blank=True, verbose_name="Thứ tự")
    created_time = models.DateTimeField(auto_now_add=True, blank=True, verbose_name="Ngày tạo")
    user = models.ForeignKey(User, verbose_name="Người tạo")
    completed=models.BooleanField(default=False, verbose_name="Đã Hoàn thành")
    completed_time=models.DateTimeField(blank=True, null=True, verbose_name="Thời gian hoàn thành")
    def __unicode__(self):
        return self.test_word.__str__() or u''
class TestingWord(models.Model):
    word=models.ForeignKey(JapaneseWord, verbose_name="Từ gốc")
    source = models.CharField(max_length=200,null=True, blank=True, verbose_name="Từ")
    kanji = models.CharField(max_length=200, null=True,blank=True, verbose_name="Từ Kanji")
    mean = models.CharField(max_length=200, null=True,blank=True, verbose_name="Nghĩa")
    added_time = models.DateTimeField(auto_now_add=True, blank=True, verbose_name="Ngày thêm")
    test_session = models.ForeignKey(TestSession, verbose_name="Phiên test")
    order=models.PositiveSmallIntegerField(verbose_name="Thứ tự")
    flag=models.BooleanField(default=False, blank=True, verbose_name="Loại kiểm tra")
    def __unicode__(self):
        return unicode(self.word) or u''

japanstudy/views.py
# -*- coding: utf-8 -*-
import random
from django.http.response import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.list import ListView
from django.utils import timezone
from japanstudy.forms import JapaneseWordAdvanceForm, JapaneseWordForm, TestWordForm,\
    TestingWordForm
from japan.utils import get_user
from models import AddWordSession, JapaneseWord

import logging
from japanstudy.models import TestWord, TestSession, TestSessionWordOrder,\
    TestingWord, JapaneseWord
log = logging.getLogger(__name__)
# Create your views here.
def home(request):
    form = JapaneseWordAdvanceForm()
    return render(request, "japanstudy/index.html", {})
# def add_japan_word_advance2(request):
#     form = JapaneseWordAdvanceForm()
#     return render(request, "japanstudy/add-jp-word-advance.html", {
#         'form':form,
#     })
def add_japan_word_advance(request):
    user = get_user(request)
    if request.method == 'POST':
        form = JapaneseWordAdvanceForm(request.POST)
        if form.is_valid():
            log.debug('valid')
            word = form.save(commit=False)
            word.user = user
            word.save()
            form.save_m2m()
            # form=JapaneseWordAdvanceForm(instance=word)
            form = JapaneseWordAdvanceForm()
        else:
            # TODO
            log.error(form.errors)
            # form=JapaneseWordAdvanceForm()
    else:
        form = JapaneseWordAdvanceForm()
    return render(request, 'japanstudy/add-jp-word-advance.html', {
        'username':user.username,
        'form':form,

    })
def add_japan_word(request):
    user = get_user(request)
    if request.method != 'POST':
        for session in AddWordSession.objects.filter(current=True, active=True, user=user):
            session.current = False
            session.save() 
        form = JapaneseWordForm()
    else:
        form = JapaneseWordForm(request.POST)
        if form.is_valid():
            word = form.save(commit=False)
            word.user = user
            word.temp = True
            word.save()
            form.save_m2m()
            # form=JapaneseWordAdvanceForm(instance=word)
            form = JapaneseWordForm()
        else:
            # TODO
            log.error(form.errors)
            # form=JapaneseWordAdvanceForm()       
    return render(request, 'japanstudy/add-jp-word.html', {
        'username':user.username,
        'form':form
    })
def add_word_success(request):
    return HttpResponse('success')
def add_test_case(request):
    user = get_user(request)
    if request.method == 'POST':
        form = TestWordForm(request.POST)
        if form.is_valid():
            test_word = form.save(commit=False)
            test_word.user = user
            test_word.save()
            form.save_m2m()
            form = TestWordForm()
        else:
            # TODO
            log.error(form.errors)
    else:
        form=TestWordForm()
    return render(request, 'japanstudy/add-test-case-word.html', {
        'username':user.username,
        'form':form
    })
class TestWordListView(ListView):
    model=TestWord
    def get_context_data(self, **kwargs):
        context=super(TestWordListView, self).get_context_data(**kwargs)
        return context
def start_test_word(request, pk):
    test_word=get_object_or_404(TestWord, pk=pk)
    words=test_word.get_shuffle_words()
    test_session=TestSession.objects.create(test_word=test_word, user=get_user(request))
    test_session.save()
    for i in range(1, len(words)+1):
        test_session_word_order=TestSessionWordOrder.objects.create(order=i, word=words[i-1])
        test_session_word_order.save()
        test_session.test_session_word_orders.add(test_session_word_order)
    return redirect('test-word-session', test_session_pk=test_session.id, order=1)
def test_word_session(request, test_session_pk, order):
    user=get_user(request)
    order=int(order)
    test_session=get_object_or_404(TestSession, pk=test_session_pk)
    word=test_session.test_session_word_orders.all()[order-1].word
    count_word=test_session.test_session_word_orders.all().count()
    if order <= 0 or order > count_word:
        raise Http404('Order invalid!')
    end = (order == count_word)
    
    if request.method == 'POST':
        testing_word=get_object_or_404(TestingWord, test_session=test_session, order=order, word=word)
        source=testing_word.word.source if not testing_word.flag else request.POST.get('source')
        mean=testing_word.word.mean if testing_word.flag else request.POST.get('mean')
        kanji=request.POST.get('kanji')

        testing_word.source=source.strip() if source else source
        testing_word.mean=mean.strip() if mean else mean
        testing_word.kanji=kanji.strip() if kanji else kanji
        testing_word.save()            
        if request.POST.get('next') and not end:
            new_order=order+1
        elif request.POST.get('prev') and order>1:
            new_order=order-1
        elif request.POST.get('finish'):
            test_session.completed=True
            test_session.completed_time=timezone.now()
            test_session.save()
            return redirect('test-word-session-result', test_session_pk=test_session.id)
        else:
            raise Http404('Invalid post!')
        return redirect('test-word-session', test_session_pk=test_session.id, order=new_order)
    else:
        testing_word_new, testing_word_created=TestingWord.objects.get_or_create(test_session=test_session, order=order,  word=word)
        if testing_word_created:
            testing_word_new.flag=bool(random.getrandbits(1))
            testing_word_new.save()
        form=TestingWordForm(current=order, flag=testing_word_new.flag, end=end, source_val=word.source if not testing_word_new.flag else testing_word_new.source, mean_val=testing_word_new.mean if not testing_word_new.flag else word.mean, kanji_val= testing_word_new.kanji, description_val=word.description)
    return render(request, 'japanstudy/testing.html',{
                                                      'username':user.username,
                                                      'form':form,
                                                    } )

class TestingWordResultView(ListView):
    model=TestingWord
    template_name = 'japanstudy/test-result.html'
    def get_context_data(self, **kwargs):
        context=super(TestingWordResultView, self).get_context_data(**kwargs)
        return context
    def get_queryset(self):
        user=get_user(self.request)
        qs = super(TestingWordResultView, self).get_queryset()
        return qs.filter(test_session__pk=self.kwargs['test_session_pk'], test_session__user=user)
class TestSessionListView(ListView):
    model=TestSession
    def get_context_data(self, **kwargs):
        context=super(TestSessionListView, self).get_context_data(**kwargs)
        return context
    def get_queryset(self):
        user=get_user(self.request)
        qs = super(TestSessionListView, self).get_queryset()
        return qs.filter(completed=True, user=user)
class JapaneseWordListView(ListView):
    model=JapaneseWord
    template_name = 'japanstudy/japaneseword_list.html'
    def get_context_data(self, **kwargs):
        context=super(JapaneseWordListView, self).get_context_data(**kwargs)
        return context
    def get_queryset(self):
        user=get_user(self.request)
        qs = super(JapaneseWordListView, self).get_queryset()
        return qs.filter(active='Y', user=user).order_by('-created_time')
    

japanstudy/templates/japanstudy/add-jp-word-advance.html
{% extends 'base.html' %}
{% block title %}Japan Study{% endblock %}
{% block content %}
{% load crispy_forms_tags %}
{% crispy form %}
{% endblock %}

japanstudy/templates/japanstudy/add-jp-word.html
{% extends 'base.html' %} {% block title %}Japan Study{% endblock %} 
{% block static %} {% load static %}
<script src="{% static "dajax/jquery.dajax.core.js" %}"></script>
{% load dajaxice_templatetags %} {% dajaxice_js_import %}
<script>
	function handleForm(data) {
		if (data == 'None') {
			return;
		}
		$('#newWords').append(data);
	}

	$(document).ready(function() {
		$('#submit-id-save_changes').click(function() {
			Dajaxice.japanstudy.add_new_words(handleForm, {
				'form' : $('#addJPWords').serialize(true)
			});
            // $('#addJPWords')[0].reset();s
            $("#addJPWords").find('input, textarea').val('');
            $("#id_source").focus();
		});
		$('#save').click(function() {
			Dajaxice.japanstudy.save_session(function(data) {
				if (data == 'True') {
					window.location.replace("{% url 'add-japan-word' %}");
				}
			});
		});
	})
</script>
{% endblock %} {% block content %}
<div class="row">
	<div class="col-md-12">
		<h3 class="form-title text-center" style="padding: 20px;">Add New
			Words</h3>
	</div>
</div>
<div class="row">
	<div class="col-lg-6 text-center">
		{% load crispy_forms_tags %} {% crispy form %}
		<div class="form-group">
			<input type="button" name="save_changes" value=" Add"
				class="btn btn-primary" id="submit-id-save_changes"> <input
				type="submit" name="cancel" value="Cancel" class="btn btn-primary"
				id="submit-id-cancel">
		</div>
	</div>
	<div class="col-lg-6 text-left word-detail">
		<div class="row">
			<div class="col-lg-12">
				<div class="" id="newWords">
					{% if words %} {% for word in words %} <input type="hidden"
						name="wordId" value="{{word.id}}" />
					<div class="row">
						<div class="col-lg-1">
							<button class="btn btn-sm btn-primary delete">
								<span class="glyphicon glyphicon-plus"></span>
							</button>
						</div>
						<div class="col-lg-3 source">わたし</div>
						<div class="col-lg-2 kanji">私</div>
						<div class="col-lg-4 mean">Tôi</div>
					</div>
					{% endfor %} {% endif %}
				</div>
				<div class="row">
					<div class="col-lg-10 text-center">
						<button class="btn btn-primary" id="save">
							<span class="glyphicon glyphicon-plus"> Save</span>
						</button>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}

japanstudy/templates/japanstudy/add-test-case-word.html
{% extends 'base.html' %} {% block title %}Japan Study{% endblock %} {% block static %} {% load static %}
<link rel="stylesheet"
	href="{% static 'datetimepicker/jquery.datetimepicker.css' %}"
	type="text/css" media="screen" />
<link rel="stylesheet"
	href="{% static 'jquery-picklist/jquery-picklist.css' %}"
	type="text/css" media="screen" />
<script src="{% static "dajax/jquery.dajax.core.js" %}"></script>
<script src="{% static "datetimepicker/jquery.datetimepicker.js" %}"></script>
<script src="{% static "jquery-picklist/jquery.ui.widget.js" %}"></script>
<script src="{% static "jquery-picklist/jquery-picklist.js" %}"></script>
{% load dajaxice_templatetags %} {% dajaxice_js_import %}
    <style >
        ul.pickList_list, .picklist{
         min-height: 500px;
        }
    </style>
<script>
	$(document).ready(function() {
		$('.datetimepicker').datetimepicker();
		// $(".picklist").pickList();
	});
</script>
{% endblock %} {% block content %}
<div class="row">
	<div class="col-md-12">
		<h3 class="form-title text-center" style="padding: 20px;">Add New
			Test Case</h3>
	</div>
</div>
<div class="row">
	<div class="col-lg-offset-1 col-lg-8 text-center">
	{% load crispy_forms_tags %} {% crispy form %}</div>
</div>

{% endblock %}

japanstudy/templates/japanstudy/add-word-line-header.html
<hr />
<div id="div_id_source" class="form-group"><label for="id_source" class="control-label  requiredField">
    Từ<span class="asteriskField">*</span> </label>

    <div class="controls "><input class="textinput textInput form-control" id="id_source" maxlength="200"
                                  name="source" type="text"></div>
</div>
<div id="div_id_mean" class="form-group"><label for="id_mean" class="control-label  requiredField">
    Nghĩa<span class="asteriskField">*</span> </label>

    <div class="controls "><input class="textinput textInput form-control" id="id_mean" maxlength="200" name="mean"
                                  type="text"></div>
</div>
<div id="div_id_kanji" class="form-group"><label for="id_kanji" class="control-label ">
    Từ Kanji
</label>

    <div class="controls "><input class="textinput textInput form-control" id="id_kanji" maxlength="200"
                                  name="kanji" type="text"></div>
</div>
<div id="div_id_romaji" class="form-group"><label for="id_romaji" class="control-label ">
    Phiên âm Latinh
</label>

    <div class="controls "><input class="textinput textInput form-control" id="id_romaji" maxlength="200"
                                  name="romaji" type="text"></div>
</div>
<div id="div_id_type" class="form-group"><label for="id_type" class="control-label ">
    Loại từ
</label>

    <div class="controls "><select class="select form-control" id="id_type" name="type">
        <option value="True" selected="selected">Hiragana</option>
        <option value="False">Katakana</option>
    </select></div>
</div>

japanstudy/templates/japanstudy/add-word-line.html
<hr />
<div id="div_id_source" class="form-group">
    <div class="controls "><input class="textinput textInput form-control" id="id_source" maxlength="200"
                                  name="source" type="text"></div>
</div>
<div id="div_id_mean" class="form-group">

    <div class="controls "><input class="textinput textInput form-control" id="id_mean" maxlength="200" name="mean"
                                  type="text"></div>
</div>
<div id="div_id_kanji" class="form-group">

    <div class="controls "><input class="textinput textInput form-control" id="id_kanji" maxlength="200"
                                  name="kanji" type="text"></div>
</div>
<div id="div_id_romaji" class="form-group">

    <div class="controls "><input class="textinput textInput form-control" id="id_romaji" maxlength="200"
                                  name="romaji" type="text"></div>
</div>
<div id="div_id_type" class="form-group">
    <div class="controls "><select class="select form-control" id="id_type" name="type">
        <option value="True" selected="selected">Hiragana</option>
        <option value="False">Katakana</option>
    </select></div>
</div>

japanstudy/templates/japanstudy/index.html
{% extends 'base.html' %}
{% block title %}Japan Study{% endblock %}
{% block content %}
Index
{% endblock %}

japanstudy/templates/japanstudy/japaneseword_list.html
{% extends 'base.html' %}
{% load my_filters %} 
{% block title %}Japanese words list{% endblock %}
{% block static %}
<style>
.test-word-rows{
font-size: 25px;
}
</style>
{% endblock %}
{% block content %}
<!-- <div class="row"> -->
<!-- 	<div class="col-md-12"> -->
<!-- 		<h3 class="form-title text-center" style="padding: 20px;">Japanese words list</h3> -->
<!-- 	</div> -->
<!-- </div> -->
<div class="row">
	<div class="col-lg-12">
	{% for w in object_list %}
		<div class="row test-word-rows">
			<div class="col-lg-4 col-md-4 col-sm-4">
				<strong>{{w.source}}</strong>
			</div>
			<div class="col-lg-4 col-md-4 col-sm-4">
				<strong>{{w.kanji}}</strong>
			</div>
			<div class="col-lg-4 col-md-4 col-sm-4">
				{{w.mean|upfirstletter}}
			</div>
		</div>
	{%	empty %}
		No Word yet.</li>
	{% endfor %}
	</div>
</div>
{% endblock %}

japanstudy/templates/japanstudy/new-word-ajax.html
{% if word %}
<input type="hidden" name="wordId" value="{{word.id}}" />
<div class="row">
	<div class="col-lg-1">
		<button class="btn btn-sm btn-primary delete">
			<span class="glyphicon glyphicon-plus"></span>
		</button>
	</div>
	<div class="col-lg-3 source">{{word.source}}</div>
	<div class="col-lg-2 kanji">{{word.kanji}}</div>
	<div class="col-lg-4 mean">{{word.mean}}</div>
</div>
{% endif %}

japanstudy/templates/japanstudy/test-result.html
{% extends 'base.html' %}

 
{% block content %}
<div class="row">
	<div class="col-md-12">
		<h3 class="form-title text-center" style="padding: 20px;">Test
			Result</h3>
	</div>
</div>
<div class="row">
	<div class="col-lg-offset-2 col-lg-8">
	{% for tw in object_list %}
        <div class="row test-word-result">
            <div class="col-lg-4">
                {% ifequal tw.source|lower tw.word.source|lower %}
                    {{tw.word.source}}
                {% else %}
                    {% if tw.source %}
                        <s>{{tw.source}}</s>
                    {% else %}
                        (empty)
                    {% endif %}
				{% endifequal %}
            </div>
            <div class="col-lg-4">
                {% ifequal tw.kanji|lower tw.word.kanji|lower %}
                    {{tw.word.kanji}}
                {% else %}
                    {% if tw.kanji %}
                        <s>{{tw.kanji}}</s>
                    {% else %}
                        (empty)
                    {% endif %}
				{% endifequal %}
			</div>
			<div class="col-lg-4">
				{% ifequal tw.mean|lower tw.word.mean|lower %}
                    {{tw.word.mean}}
                {% else %}
                    {% if tw.mean %}
                        <s>{{tw.mean}}</s>
                    {% else %}
                        (empty)
                    {% endif %}
				{% endifequal %}
			</div>

		</div>
		<div class="row test-word-source">
            <div class="col-lg-4">
				{% ifnotequal tw.source|lower tw.word.source|lower %}
                    {{tw.word.source}}
				{% endifnotequal %}
			</div>
            <div class="col-lg-4">
                {% ifnotequal tw.kanji|lower tw.word.kanji|lower %}
                    {{tw.word.kanji}}
				{% endifnotequal %}
			</div>
			<div class="col-lg-4">
				{% ifnotequal tw.mean|lower tw.word.mean|lower %}
                    {{tw.word.mean}}
				{% endifnotequal %}
			</div>


		</div>

        <hr />
	{%	empty %}
		No Word yet.</li>
	{% endfor %}
    {% if object_list %}
        <div class="row">
            <div class="col-lg-offset-4 col-lg-4">
                <a href="{% url 'start-test-word' object_list.0.test_session.test_word.id %}" class="btn btn-success">
                        <span> Try again !</span>
                </a>
            </div>
        </div>
    {% endif %}
	</div>
</div>
{% endblock %}

japanstudy/templates/japanstudy/testing.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
 
{% block content %}
   {% crispy form %}
{% endblock %}

japanstudy/templates/japanstudy/testsession_list.html
{% extends 'base.html' %} {% block title %}Test cases list{% endblock %}
{% block static %}
<style>
.test-word-rows{
font-size: 25px;
}
</style>
{% endblock %}
{% block content %}
<div class="row">
	<div class="col-md-12">
		<h3 class="form-title text-center" style="padding: 20px;">Test
			Session list</h3>
	</div>
</div>
<div class="row">
	<div class="col-lg-offset-2 col-lg-8">
	{% for ts in object_list %}
		<div class="row test-word-rows">
			<div class="col-lg-5">
				<a href="{% url 'test-word-session-result' ts.id %}"><strong>{{ts.test_word.title}}</strong></a>
			</div>
			<div class="col-lg-6">
				{% if ts.completed_time %}{{ts.completed_time}}{% endif %}
			</div>
		</div>
	{%	empty %}
		No Test Session yet.</li>
	{% endfor %}
	</div>
</div>
{% endblock %}

japanstudy/templates/japanstudy/testword_list.html
{% extends 'base.html' %} {% block title %}Test cases list{% endblock %}
{% block static %}
<style>
.test-word-rows{
font-size: 25px;
}
</style>
{% endblock %}
{% block content %}
<div class="row">
	<div class="col-md-12">
		<h3 class="form-title text-center" style="padding: 20px;">Test
			cases list</h3>
	</div>
</div>
<div class="row">
	<div class="col-lg-offset-2 col-lg-8">
	{% for tw in object_list %}
		<div class="row test-word-rows">
			<div class="col-lg-5">
				<a href="#"><strong>{{tw.title}}</strong></a>
			</div>
			<div class="col-lg-6">
				{% if tw.start_date %}{{tw.start_date}}{% endif %}
			</div>
			<div class="col-lg-1">
				<a href="{% url 'start-test-word' tw.id %}" class="btn btn-primary">
					<span> Start</span>
				</a>
			</div>
		</div>
	{%	empty %}
		No Test Word yet.</li>
	{% endfor %}
	</div>
</div>
{% endblock %}